apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: loki
spec:
  loki:
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
      flush_mode: immediate
      overflow_action: drop_oldest_chunk
      flush_at_shutdown: true
      flush_thread_count: 5
      compress: gzip
    configure_kubernetes_labels: true
    extract_kubernetes_labels: true
    url: http://loki-gateway.loki.svc.cluster.local