apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: loki
spec:
  loki:
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_zone: Europe/Berlin
    configure_kubernetes_labels: true
    extract_kubernetes_labels: true
    url: http://loki-gateway.loki.svc.cluster.local