apiVersion: v1
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-gateway.loki.svc.cluster.local
      access: proxy
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: '1'
  name: loki-datasource
  namespace: cattle-monitoring-system